In [2]:
from tensorflow.keras.preprocessing.text import one_hot

In [3]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [4]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [6]:
### Vocabulary size
voc_size=10000

# One Hot Representation   

### Index from Dictionary

In [8]:
onehot_repr=[one_hot(words,voc_size)for words in sent] 
print(onehot_repr)

[[8946, 1200, 2520, 3975], [8946, 1200, 2520, 8421], [8946, 7524, 2520, 6854], [2736, 5870, 371, 787, 5721], [2736, 5870, 371, 787, 9520], [5141, 8946, 1500, 2520, 184], [4377, 247, 2858, 787]]


## Word Embedding Represntation

In [9]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [10]:
import numpy as np

In [13]:
sent_length=8
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 8946 1200 2520 3975]
 [   0    0    0    0 8946 1200 2520 8421]
 [   0    0    0    0 8946 7524 2520 6854]
 [   0    0    0 2736 5870  371  787 5721]
 [   0    0    0 2736 5870  371  787 9520]
 [   0    0    0 5141 8946 1500 2520  184]
 [   0    0    0    0 4377  247 2858  787]]


In [14]:
dim = 10

In [15]:
model=Sequential()
model.add(Embedding(voc_size,10,input_length=sent_length))
model.compile('adam','mse')

Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor


In [16]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding (Embedding)        (None, 8, 10)             100000    
Total params: 100,000
Trainable params: 100,000
Non-trainable params: 0
_________________________________________________________________


In [17]:
print(model.predict(embedded_docs))

[[[-8.18483531e-05  4.61529940e-04  1.45218261e-02  2.52038129e-02
    9.32026654e-04 -1.80888399e-02 -1.39846317e-02  3.18042301e-02
   -4.12664562e-03  2.42862850e-03]
  [-8.18483531e-05  4.61529940e-04  1.45218261e-02  2.52038129e-02
    9.32026654e-04 -1.80888399e-02 -1.39846317e-02  3.18042301e-02
   -4.12664562e-03  2.42862850e-03]
  [-8.18483531e-05  4.61529940e-04  1.45218261e-02  2.52038129e-02
    9.32026654e-04 -1.80888399e-02 -1.39846317e-02  3.18042301e-02
   -4.12664562e-03  2.42862850e-03]
  [-8.18483531e-05  4.61529940e-04  1.45218261e-02  2.52038129e-02
    9.32026654e-04 -1.80888399e-02 -1.39846317e-02  3.18042301e-02
   -4.12664562e-03  2.42862850e-03]
  [-2.03798413e-02  7.68299028e-03  5.06342575e-03 -2.62316000e-02
   -2.63322126e-02 -2.98881661e-02  2.12768205e-02 -1.20320804e-02
   -2.53356937e-02 -2.86600739e-03]
  [-2.49512196e-02  2.17353217e-02  4.72772457e-02  1.83178298e-02
    3.16863097e-02  9.79610533e-03 -1.15179308e-02 -2.55742427e-02
    2.64602937e-

In [18]:
embedded_docs[0]

array([   0,    0,    0,    0, 8946, 1200, 2520, 3975])

In [20]:
print(model.predict(embedded_docs)[0])

[[-8.18483531e-05  4.61529940e-04  1.45218261e-02  2.52038129e-02
   9.32026654e-04 -1.80888399e-02 -1.39846317e-02  3.18042301e-02
  -4.12664562e-03  2.42862850e-03]
 [-8.18483531e-05  4.61529940e-04  1.45218261e-02  2.52038129e-02
   9.32026654e-04 -1.80888399e-02 -1.39846317e-02  3.18042301e-02
  -4.12664562e-03  2.42862850e-03]
 [-8.18483531e-05  4.61529940e-04  1.45218261e-02  2.52038129e-02
   9.32026654e-04 -1.80888399e-02 -1.39846317e-02  3.18042301e-02
  -4.12664562e-03  2.42862850e-03]
 [-8.18483531e-05  4.61529940e-04  1.45218261e-02  2.52038129e-02
   9.32026654e-04 -1.80888399e-02 -1.39846317e-02  3.18042301e-02
  -4.12664562e-03  2.42862850e-03]
 [-2.03798413e-02  7.68299028e-03  5.06342575e-03 -2.62316000e-02
  -2.63322126e-02 -2.98881661e-02  2.12768205e-02 -1.20320804e-02
  -2.53356937e-02 -2.86600739e-03]
 [-2.49512196e-02  2.17353217e-02  4.72772457e-02  1.83178298e-02
   3.16863097e-02  9.79610533e-03 -1.15179308e-02 -2.55742427e-02
   2.64602937e-02 -2.89031863e-02